language: ruby
cache: bundler
env:
  - DB=sqlite3
gemfile:
  - gemfiles/rails_5.1.gemfile
  - gemfiles/rails_5.2.gemfile
  - gemfiles/rails_6.0.gemfile
rvm:
  - 2.5.6
  - 2.6.4
before_install: gem install bundler -v 1.17.3
before_script:
  - bundle exec rake db:setup RAILS_ENV=test
script:
  - bundle exec rspec
  - bundle exec rubocop --config .rubocop.yml
